# Generated by Django 5.1 on 2024-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
