# Generated by Django 5.1 on 2024-11-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0002_alter_pages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], max_length=200),
        ),
    ]
