# Generated by Django 5.1 on 2024-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0003_alter_pages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.CharField(choices=[('0', 'Disable'), ('1', 'Enable')], max_length=200),
        ),
    ]
