# Generated by Django 5.1 on 2024-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0004_alter_pages_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='iframe_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.CharField(choices=[('1', 'Enable'), ('0', 'Disable')], default='1', max_length=200),
        ),
    ]
