# Generated by Django 5.1 on 2024-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0005_pages_iframe_code_alter_pages_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='iframe_code',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
