# Generated by Django 5.1 on 2024-11-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0007_userforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForms',
            new_name='UserForm',
        ),
    ]
