# Generated by Django 5.1 on 2024-11-23 13:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0008_rename_userforms_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_owner_phone', models.CharField(max_length=15)),
                ('vehicle_owner_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriverTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=100)),
                ('driver_email', models.CharField(max_length=100)),
                ('is_training_needed', models.CharField(max_length=2)),
                ('training_name', models.CharField(max_length=100)),
                ('training_date', models.DateField()),
                ('driver_training_status', models.CharField(max_length=2)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets_management.vehicleregister')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_sent', models.CharField(max_length=2)),
                ('email_date', models.DateField(default=datetime.datetime(2024, 11, 23, 19, 0, 21, 715800))),
                ('vehicle_condition', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets_management.vehicleregister')),
            ],
        ),
    ]
