# Generated by Django 5.1 on 2024-11-23 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets_management', '0009_vehicleregister_drivertraining_vehicletrackrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregister',
            name='vehicle_reg_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vehicletrackrecord',
            name='email_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
